import Link from "next/link";
import Image from "next/image";
import { getRuntimeBrand } from "@/lib/white-label/settings";
import FunnelTracker from "@/components/marketing/FunnelTracker";
import CheckoutButton from "@/components/marketing/CheckoutButton";

export const dynamic="force-dynamic";
const benefits=["Cerita personal sesuai profil dan usia anak","Teks dapat direview sebelum ilustrasi dibuat","Ilustrasi, audio, moral, doa dan parent guide","Flipbook untuk dibaca bersama anak","English Learning: video, PDF, vocabulary + TTS dan kuis","Koleksi cerita dan progress membaca","Bisa dipasang di HP sebagai aplikasi PWA"];
export default async function SuperKids(){const brand=await getRuntimeBrand();return <main className="min-h-screen bg-surface text-ink"><FunnelTracker event="ViewContent" product="PBSK-SUPER-KIDS" />
<header className="px-5 py-5"><div className="mx-auto flex max-w-6xl items-center justify-between"><Link href="/" className="flex items-center gap-2"><Image src={brand.logoSrc||"/logo.png"} alt={brand.name} width={48} height={48} className="rounded-xl"/><b>Papa Bonski</b></Link><Link href="/login" className="text-sm font-extrabold">Login Member</Link></div></header>
<section className="px-5 pb-16 pt-10"><div className="mx-auto grid max-w-6xl items-center gap-10 md:grid-cols-2"><div><span className="rounded-full bg-brand-accent/40 px-4 py-2 text-xs font-black uppercase tracking-wider">Papa Bonski Super Kids</span><h1 className="mt-5 text-5xl font-extrabold leading-[1.08]">Buat waktu belajar anak terasa seperti petualangan yang dibuat khusus untuknya.</h1><p className="mt-5 text-lg text-ink-soft">Bunda memilih profil anak, tema dan kebutuhan hari ini. Papa Bonski membantu membuat cerita personal yang bisa dibaca, didengar, disimpan dan dinikmati bersama.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><CheckoutButton className="btn-primary text-center"/><a href="#cara-kerja" className="btn-secondary text-center">Lihat Cara Kerja</a></div><p className="mt-3 text-xs text-ink-faint">Checkout diproses melalui halaman pembayaran resmi Papa Bonski.</p></div>
<div className="rounded-[2.5rem] bg-surface-card p-5 shadow-xl ring-1 ring-black/5"><div className="rounded-[2rem] bg-gradient-to-br from-brand-primary/15 to-brand-accent/20 p-7"><div className="mx-auto max-w-sm rounded-3xl bg-white p-5 shadow-lg"><p className="text-xs font-black text-brand-primary">CONTOH PENGALAMAN</p><h3 className="mt-2 text-2xl font-extrabold">Hari ini, cerita apa yang dibutuhkan si kecil?</h3><div className="mt-4 grid grid-cols-2 gap-2 text-sm font-bold"><span className="rounded-xl bg-surface p-3">😴 Susah tidur</span><span className="rounded-xl bg-surface p-3">🥦 Tidak mau sayur</span><span className="rounded-xl bg-surface p-3">🏫 Takut sekolah</span><span className="rounded-xl bg-surface p-3">📱 Gadget</span></div><div className="mt-4 rounded-xl bg-brand-primary p-3 text-center font-extrabold text-white">✨ Buat Cerita Personal</div></div></div></div></div></section>
<section id="cara-kerja" className="bg-white/60 px-5 py-16"><div className="mx-auto max-w-6xl"><p className="text-center text-sm font-black uppercase tracking-widest text-brand-primary">Cara Kerja</p><h2 className="mx-auto mt-2 max-w-2xl text-center text-3xl font-extrabold">Dari kebutuhan anak hari ini menjadi cerita yang bisa dinikmati bersama.</h2><div className="mt-9 grid gap-4 md:grid-cols-4">{[["1","Buat profil anak","Nama, usia, foto dan karakter dapat digunakan kembali."],["2","Pilih kebutuhan","Pilih tema, masalah hari ini, level bahasa dan gaya ilustrasi."],["3","Review cerita","Teks dibuat lebih dulu agar Bunda dapat meninjau dan mengedit."],["4","Baca & dengarkan","Setelah disetujui, ilustrasi dan audio dibuat untuk flipbook."]].map(([n,t,d])=><div key={n} className="rounded-3xl bg-surface-card p-6 shadow-sm ring-1 ring-black/5"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-brand-primary font-black text-white">{n}</div><h3 className="mt-4 font-extrabold">{t}</h3><p className="mt-2 text-sm text-ink-soft">{d}</p></div>)}</div></div></section>
<section className="px-5 py-16"><div className="mx-auto max-w-5xl"><div className="grid gap-8 md:grid-cols-2"><div><p className="text-sm font-black uppercase tracking-widest text-brand-primary">Yang Didapat</p><h2 className="mt-2 text-3xl font-extrabold">Bukan hanya generator cerita.</h2><p className="mt-4 text-ink-soft">Super Kids dirancang sebagai ruang belajar keluarga yang bisa terus digunakan.</p></div><div className="space-y-3">{benefits.map(b=><div key={b} className="flex gap-3 rounded-2xl bg-surface-card p-4 ring-1 ring-black/5"><span>✅</span><span className="font-bold">{b}</span></div>)}</div></div></div></section>
<section className="bg-brand-primary px-5 py-16 text-white"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-black uppercase tracking-widest opacity-80">Siap mencoba?</p><h2 className="mt-3 text-4xl font-extrabold">Mulai Papa Bonski Super Kids untuk si kecil.</h2><p className="mx-auto mt-4 max-w-xl opacity-90">Setelah pembayaran terverifikasi, akses customer akan disiapkan dan dapat digunakan melalui login Papa Bonski.</p><CheckoutButton className="mt-7 inline-flex rounded-full bg-white px-7 py-4 font-extrabold text-brand-primary shadow-lg"/></div></section>
<section className="px-5 py-12"><div className="mx-auto max-w-3xl"><h2 className="text-center text-2xl font-extrabold">Pertanyaan yang sering ditanyakan</h2><div className="mt-6 space-y-3">{[["Apakah harus install dari Play Store?","Tidak. Papa Bonski dapat dibuka lewat browser dan dipasang ke Home Screen sebagai PWA pada perangkat yang mendukung."],["Apakah customer perlu mengatur Supabase atau Gemini?","Tidak. Konfigurasi teknis dikelola oleh sistem Papa Bonski."],["Bagaimana saya masuk setelah membeli?","Gunakan email pembelian di halaman Login Member. Sistem akan mengirim magic link untuk masuk."],["Apakah bisa dipakai di HP dan tablet?","Ya. Antarmuka dirancang untuk web mobile dan PWA."]].map(([q,a])=><details key={q} className="rounded-2xl bg-surface-card p-5 ring-1 ring-black/5"><summary className="cursor-pointer font-extrabold">{q}</summary><p className="mt-3 text-sm text-ink-soft">{a}</p></details>)}</div></div></section>
</main>}
