import Link from "next/link";
import Image from "next/image";
import { getRuntimeBrand } from "@/lib/white-label/settings";
import FunnelTracker from "@/components/marketing/FunnelTracker";

export const dynamic="force-dynamic";
export default async function Home(){const brand=await getRuntimeBrand();return <main className="min-h-screen bg-surface text-ink">
<FunnelTracker event="BrandHomeView" />
<section className="px-5 py-8"><div className="mx-auto max-w-6xl"><nav className="flex items-center justify-between"><div className="flex items-center gap-3"><Image src={brand.logoSrc||"/logo.png"} alt={brand.name} width={56} height={56} className="rounded-2xl"/><b className="text-xl">Papa Bonski</b></div><div className="flex gap-3 text-sm font-extrabold"><Link href="/login">Login</Link><Link href="/super-kids" className="rounded-full bg-brand-primary px-4 py-2 text-white">Super Kids</Link></div></nav>
<div className="grid items-center gap-10 py-16 md:grid-cols-2"><div><p className="text-sm font-black uppercase tracking-[.18em] text-brand-primary">Belajar • Bermain • Bertumbuh</p><h1 className="mt-4 text-5xl font-extrabold leading-tight">Temani si kecil belajar dengan cara yang lebih personal dan menyenangkan.</h1><p className="mt-5 max-w-xl text-lg text-ink-soft">Papa Bonski menghadirkan cerita personal, English learning, aktivitas edukatif, buku digital, dan pengalaman belajar keluarga dalam satu ekosistem.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/super-kids" className="btn-primary">Kenali Super Kids</Link><Link href="/login" className="btn-secondary">Sudah membeli? Login</Link></div></div>
<div className="rounded-[2.5rem] bg-surface-card p-7 shadow-xl ring-1 ring-black/5"><div className="rounded-[2rem] bg-brand-primary/10 p-7"><p className="text-sm font-extrabold text-brand-primary">PRODUK UTAMA</p><h2 className="mt-2 text-3xl font-extrabold">Papa Bonski Super Kids</h2><p className="mt-3 text-ink-soft">Cerita personal untuk anak, audio, flipbook, parent guide, dan English Learning.</p><Link href="/super-kids" className="mt-6 inline-flex rounded-full bg-brand-primary px-6 py-3 font-extrabold text-white">Lihat Selengkapnya →</Link></div></div></div>
<div className="grid gap-4 pb-16 md:grid-cols-3">{[["✨","Cerita Personal","Cerita dibuat sesuai profil, usia, dan kebutuhan anak."],["🎬","English Learning","Video, vocabulary, audio, PDF dan kuis."],["🎨","Produk Edukatif","Buku mewarnai, worksheet, dan materi belajar Papa Bonski."]].map(([i,t,d])=><div key={t} className="rounded-3xl bg-surface-card p-6 ring-1 ring-black/5"><div className="text-3xl">{i}</div><h3 className="mt-3 text-xl font-extrabold">{t}</h3><p className="mt-2 text-sm text-ink-soft">{d}</p></div>)}</div>
</div></section></main>}
