import Link from "next/link";
import { createSupabaseAdminClient } from "@/lib/supabase/server";
export const dynamic="force-dynamic";
export default async function SellerPage(){
  let stats={customers:0,orders:0,paid:0,active:0,revenue:0}; let recent:any[]=[]; let configured=true;
  try{const db=createSupabaseAdminClient(); const [{count:customers},{count:orders},{count:active},{data:paidRows},{data:recentRows}]=await Promise.all([
    db.from("customers").select("*",{count:"exact",head:true}), db.from("orders").select("*",{count:"exact",head:true}), db.from("subscriptions").select("*",{count:"exact",head:true}).eq("status","active"), db.from("orders").select("amount").eq("status","paid"), db.from("customers").select("id,customer_code,name,email,status,created_at").order("created_at",{ascending:false}).limit(8)
  ]); stats={customers:customers||0,orders:orders||0,paid:paidRows?.length||0,active:active||0,revenue:(paidRows||[]).reduce((s:any,r:any)=>s+Number(r.amount||0),0)}; recent=recentRows||[];}catch{configured=false;}
  return <main className="min-h-[100dvh] bg-surface px-5 py-10 text-ink"><div className="mx-auto max-w-6xl">
    <p className="text-xs font-extrabold uppercase tracking-[0.18em] text-brand-primary">OrderHero Live Platform V5.4</p><h1 className="mt-2 text-3xl font-extrabold">Papa Bonski Seller Center</h1><p className="mt-2 text-sm text-ink-soft">Customer, order, subscription, activation, dan funnel dalam satu pusat operasional.</p>
    {!configured&&<div className="mt-6 rounded-2xl bg-amber-50 p-5 ring-1 ring-amber-200">Jalankan migration <code>0002_v5_multi_customer.sql</code> agar dashboard V5 aktif.</div>}
    <div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Customers",stats.customers],["Orders",stats.orders],["Paid",stats.paid],["Active",stats.active],["Revenue",new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(stats.revenue)]].map(([a,b])=><div key={String(a)} className="rounded-2xl bg-surface-card p-5 ring-1 ring-black/[.06]"><div className="text-xs font-bold uppercase text-ink-soft">{a}</div><div className="mt-2 text-2xl font-black">{b}</div></div>)}</div>
    <div className="mt-6 grid gap-4 md:grid-cols-3"><Link href="/seller/customers" className="rounded-2xl bg-surface-card p-5 ring-1 ring-black/[.06]"><div className="text-2xl">👥</div><h2 className="mt-2 font-extrabold">Customers</h2><p className="text-sm text-ink-soft">Daftar customer dan status akses.</p></Link><Link href="/seller/orderhero" className="rounded-2xl bg-surface-card p-5 ring-1 ring-black/[.06]"><div className="text-2xl">💳</div><h2 className="mt-2 font-extrabold">OrderHero Live</h2><p className="text-sm text-ink-soft">Webhook, purchase activation, dan mapping.</p></Link><Link href="/seller/deploy" className="rounded-2xl bg-surface-card p-5 ring-1 ring-black/[.06]"><div className="text-2xl">🔗</div><h2 className="mt-2 font-extrabold">Integrasi</h2><p className="text-sm text-ink-soft">Endpoint OrderHero dan deployment.</p></Link><Link href="/owner" className="rounded-2xl bg-surface-card p-5 ring-1 ring-black/[.06]"><div className="text-2xl">✅</div><h2 className="mt-2 font-extrabold">System Readiness</h2><p className="text-sm text-ink-soft">Cek kesiapan platform.</p></Link></div>
    <section className="mt-6 rounded-2xl bg-surface-card p-6 ring-1 ring-black/[.06]"><h2 className="text-xl font-extrabold">Customer terbaru</h2><div className="mt-4 space-y-3">{recent.length?recent.map(c=><div key={c.id} className="flex flex-wrap items-center justify-between gap-2 border-b border-black/5 pb-3"><div><b>{c.name}</b><div className="text-xs text-ink-soft">{c.customer_code} · {c.email||"tanpa email"}</div></div><span className="rounded-full bg-green-50 px-3 py-1 text-xs font-bold">{c.status}</span></div>):<p className="text-sm text-ink-soft">Belum ada customer V5.</p>}</div></section>
  </div></main>;
}
