#!/usr/bin/env node
import fs from 'node:fs';
import crypto from 'node:crypto';
import readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';

const rl = readline.createInterface({ input, output });
const ask = async (q, def='') => {
  const a = (await rl.question(`${q}${def ? ` [${def}]` : ''}: `)).trim();
  return a || def;
};
const secret = () => crypto.randomBytes(32).toString('hex');

console.log('\n🐻 Papa Bonski Super Kids — Commercial Edition V4\n');
console.log('Wizard ini membuat .env.local. Kunci rahasia tidak dikirim ke mana pun.\n');

const supabaseUrl = await ask('Supabase Project URL (https://xxxx.supabase.co)');
const anonKey = await ask('Supabase anon/public key');
const serviceKey = await ask('Supabase service_role key');
const geminiKey = await ask('Gemini API key');
const adminSecret = await ask('Password admin', secret().slice(0,20));
const workerSecret = secret();
const kieKey = await ask('KIE API key (opsional)', '');
const customerName = await ask('Nama customer / bisnis (opsional)', '');
const installationId = await ask('Installation ID', `PBSK-${crypto.randomBytes(4).toString('hex').toUpperCase()}`);
const appUrl = await ask('Production URL (opsional, contoh https://app.domain.com)', '');

const required = [supabaseUrl, anonKey, serviceKey, geminiKey];
if (required.some(v => !v)) {
  console.error('\n❌ Setup dibatalkan: data wajib belum lengkap.');
  process.exitCode = 1;
  rl.close();
  process.exit();
}
if (!/^https:\/\/.+\.supabase\.co\/?$/.test(supabaseUrl)) {
  console.warn('⚠️  URL Supabase terlihat tidak biasa. Periksa kembali setelah setup.');
}

const env = `# Papa Bonski Super Kids — generated by Commercial Edition V4
NEXT_PUBLIC_SUPABASE_URL="${supabaseUrl.replace(/\/$/,'')}"
NEXT_PUBLIC_SUPABASE_ANON_KEY="${anonKey}"
SUPABASE_SERVICE_ROLE_KEY="${serviceKey}"

STORY_WORKER_SECRET="${workerSecret}"
STORY_WORKER_AUTOKICK="true"
ADMIN_DASHBOARD_SECRET="${adminSecret}"

GEMINI_API_KEY="${geminiKey}"
IMAGE_PROVIDER="gemini"
IMAGE_RESOLUTION="1K"
${kieKey ? `KIE_API_KEY="${kieKey}"\nIMAGE_KIE_FALLBACK="true"\n` : ''}NEXT_PUBLIC_STORY_QUEUE_POLL_MS="2500"
NEXT_PUBLIC_STORY_QUEUE_MAX_POLLS="240"
PAPA_BONSKI_CUSTOMER_NAME="${customerName}"
PAPA_BONSKI_INSTALLATION_ID="${installationId}"
${appUrl ? `NEXT_PUBLIC_APP_URL="${appUrl.replace(/\/$/, '')}"\n` : ''}`;
fs.writeFileSync('.env.local', env, { mode: 0o600 });
rl.close();
console.log('\n✅ .env.local berhasil dibuat.');
console.log('1) Jalankan SQL: supabase/migrations/0001_init.sql di Supabase SQL Editor');
console.log('2) Aktifkan Authentication → Providers → Anonymous');
console.log('3) Jalankan: npm run dev');
console.log('4) Buka: http://localhost:3000/owner untuk Commercial Readiness\n');
